import Head from 'next/head'
import { Container, Box, Image, Heading, Text, Link, StackDivider, VStack } from '@chakra-ui/react'
import Layout from '@/components/Layout'
import Post from '@/components/Post'
import { getAllPosts } from '@/services/servicePosts'
import Newsletter from '@/components/Newsletter'

// import Image from 'next/image'

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Mi Blog</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        {/* Hero */}
        <Box bg='purple.300'>
          <Container maxW={1200} minH={720} display='flex' flexDir={['column', 'row']} alignItems='center' justifyContent='center' gap={4}>
            <Image src='https://placekitten.com/360/360' alt='profile' rounded='full' w={360} h={360} />
            <Box dislay='flex' flexDir='column' flexGrow={[0, 1]}>
              <Heading as='h1' textAlign='center' fontSize={[48, 64]}>Hi, I’m Darshan<br /> Sharma</Heading>
              <Text textAlign='center' fontSize={[24, 36]}>It is good to have you here</Text>
            </Box>
          </Container>
        </Box>
        {/* About Me */}
        <Box bg='white'>
          <Container maxW={1200} minH={720} display='flex' flexDir='column' justifyContent='center' gap={16}>
            <Text fontSize={[36, 64]} textAlign='center'>
              Here I write stuff related to computer, anime, movies and what’s happening in my life?
            </Text>
            <Link href='/contact' fontSize={[28, 48]} textAlign='right'>More about me</Link>
          </Container>
        </Box>
        {/* New Posts */}
        <Box display='flex' flexDir='column' justifyContent='center' bg='purple.300' minH={720} px={2}>
          <VStack maxW={1200} divider={<StackDivider borderColor='gray.600' />} spacing={4} py={4} mx='auto'>
            {
            posts && posts.map((item) => (
              <Post key={item.id} item={item} />
            ))
            }
          </VStack>
          <Box display='flex' justifyContent='flex-end' w={1200} mx='auto'>
            <Link href='/blog' fontSize={[18, 24]}>Read more posts</Link>
          </Box>
        </Box>
        <Box bg='white' id='subscribe'>
          <Container maxW={1200} minH={400} display='flex' flexDir='column' justifyContent='center' gap={8}>
            <Text fontSize={[20, 36]} textAlign='center'>
              Would you like to recieve emails of my posts every friday, if yes then consider subscribing
            </Text>
            <Newsletter />
          </Container>
        </Box>
      </Layout>
    </>
  )
}

export async function getServerSideProps() {
  const posts = await getAllPosts()
  return {
    props: {
      posts: posts.slice(0, 2)
    }
  }
}
